name: Run PHPUnit tests

on:
  push:
    branches:
      - main 

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: testing
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, mysql, pdo_mysql

    - name: Prepare environment
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        cp .env.example .env
        php artisan key:generate
        php artisan migrate --force

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
      run: |
        npm install
        npm run build

    - name: Run PHPUnit tests
      run: php artisan test